# Generated by Django 4.1.6 on 2023-02-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_id',
        ),
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
