# Generated by Django 4.1.6 on 2023-02-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0002_remove_address_person_id_remove_contact_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='FIRSTAPPLICATION.name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
